<?php

/**
 * 人员管理
 * @author liuminchao
 */
return array(
    //----------标题---------------
    'contentHeader' => 'Chemical Details',
    'bigMenu' => 'Chemical Management',
    'smallHeader List' => 'Chemical List',
    'smallHeader New' => 'Add Chemical',
    'smallHeader Edit' => 'Edit Chemical',
    'Statistics contentHeader' => 'Chemical Statistics',
    //---------表单----------------
    'chemical_edit' =>'edit',
    'chemical_delete' => 'delete',
    'chemical_type' => 'Chemical Type',
    'chemical_name' => 'Chemical Name',
    'chemical_content' => 'Chemical Details',
    'chemical_id' => 'Registration No.',
    'chemical_img'=> 'Chemical Photo',
    'permit_img'=> 'License Images',
    'permit_info'=> 'License Info',
    'permit_startdate'=>'License Start Date',
    'permit_enddate'=> 'License End Date',
    'status' => 'Status',
    'Action' => 'Actions',
    'chemical_num' => 'Chemical Number',
    'record_time' => 'Created On',
    'Add Chemical' => 'Add Chemical',
    'Logout Chemical' =>'Delete Chemical',
    'Edit Chemical' =>'Edit Chemical',
    'STATUS_NORMAL'=> 'Available',
    'STATUS_DISABLE'=> 'Not Available',
    'related_chemical'=>'Add New Chemical',
    'Assign Chemical' => 'Select equipment by chemical type',
    'select_cnt'    => 'Selected Count',
    'Chemical_certificate' => 'Certificate',
    'Chemical_batch_export' => 'Export chemical Summary Report',
    'compound' => 'Hazardous Substance/Compound',
    'usage' => 'Usage',
    'properties' => 'Hazardous Properties',
    'storage_require' => 'Storage Requirements',
    'personal_protection' => 'Personal Protection',
    'first_aid_measures' => 'Health Hazards & First Aid Measures',
    'other_measures' => 'Environmental/Other Measures',
    'person_in_charge' => 'Person-in-charge',
    //-----------验证信息----------------
    'Error Chemical_id is null'=> 'This field is compulsory.',
    'Error Chemical_name is null'=> 'Please input Chemical Name.',
    'Error Upload_file is null' => 'Please upload the correct file',
    'Error Chemical_id is exist' => 'The same registration number already exists.',
    'Error Upload_pic is null' => 'Please upload photo.',
    'Error Chemical_type is null' => 'Please check for incomplete information.',
    'Error Chemical_content is null' => 'Certificate content cannot be left empty',
    'Error chemical is in program' =>  'The chemical has unfinished projects:',
    'Error chemical do not' => 'can\'t operate',
    'Error Chemical is exist' => 'The  Registration No. Already Exist at',
);