<?php

/**
 * 平台
 * @author LiuXiaoyuan
 */
return array(
    'contentHeader' => '控制面板',
    'Menu pedit' => '修改个人信息',
    'Menu reset' => '登录密码重置',
    'Menu logout' => '退出登录',
    'Home' => '首页',
    'no auth' => '您没有权限执行该操作！',
    'smanager' => '系统管理员',
    'cmanager' => '承包商管理员',
    'Tip Password' => '为确保安全，请修改您的初始密码',
    'Menu Operator' => '操作员管理',
    'Menu Platform' => '平台人数',
    'Menu Optlog' => '系统日志',
    'Menu System' => '系统管理',
    'Menu Maincomp' => '总包公司管理',
    'Menu Subcomp' => '分包公司管理',
    'Menu Comp' => '承包商管理',
    'Menu CompInfo' => '基本信息管理',
    'Menu Maincomp User' => '人员信息维护',
    'Menu Maincomp Role' => '岗位管理',
    'Menu Main User' => '总包人员管理',
    'Menu Project List' => '项目维护',
    'Menu Project MC'   =>  '总包项目',
    'Menu Project SC'   =>  '分包项目',
    'Menu Assign User' => '指派人员',
    'Menu Project' => '项目管理',
    'Menu Project Report'   =>  '项目工时统计',
    'Menu Statistics' => '统计',
    'Menu Notification' => '通知',
    'Menu Certexpiry' => '证书到期',
    'Business Statistics' => '业务统计',
    'Business Statistics Graph' => '业务统计图',
    
    'Menu Comp Staff' => '人员管理',
    'Menu Comp Worker' => '工人管理',
    'Menu Comp Role' => '岗位管理',
    'Menu Aptitude' => '资质查询',
    'Menu Staff' => '人员信息管理',
    'Menu My Project' => '我的项目',
    'Menu Workflow' => '工作流配置',
    'Menu Licedown' => '许可证下载',
    'Menu Lice' => '许可证审批',
    'Enter' => '进入',
    'Prev' => '前页',
    'Next' => '后页',
    'loading' => '我正在努力加载...',
    'Project Statistical Charts' => '项目统计图表',
    'Company Statistical Charts' => '公司统计图表',
    'PTW Type Statistics' => 'PTW Type Statistics',
    'NCR Type Statistics' => 'NCR Type Statistics',
    'Good Practices Statistics' => 'Good Practices Statistics',
    'Test Charts'  => 'PTW Status Statistics',
    'Menu Violation Ranking' => '违规排名',
    'Menu Meetingdown' => '会议文档下载',
    'Menu Meetingdown Plan' => '会议计划',
    'Menu Meeting' => '工具箱会议',
    'Menu Safety Promotion Programme' => '安全推广计划',
    'Menu Wshdown' => '文档下载',
    'Menu Wsh' => '安全检查',
    'Menu Qaqcdown' => '文档下载',
    'Menu Qaqc' => 'QA/QC检查',
    'Menu Training' => '下载报告',
    'Menu Train' => '培训',
    'Menu meeting' => '会议',
    'Menu Accident down' => '下载报告',
    'Menu Accident' => '意外',

    'Menu Attend'   =>  '考勤应用',
    'Menu Attend2'  =>  '考勤管理',
    'Menu Attend device'=>  '设备管理',
    'Menu Attend dayManage'=>  '班次时段管理',
    'Menu Attend policyManage'=>  '排班管理',
    'Menu Attend schedule'=>  '考勤规则',
    'Menu Attend manual'=>  '手动考勤',
    'Menu Attend record'=>  '考勤记录',
    'Menu Attend failure record' => '失败记录',
    'Menu Attend report'=>  '考勤报表',
    
    
);
