<?php

/**
 * 操作员管理
 * @author LiuMinchao
 */
return array(
    //--------------标题-----------------
    'contentHeader' => '项目管理',
    'bigMenu' => '项目管理',
    'smallHeader List' => '任务列表',
    'smallHeader New' => '任务添加',
    'smallHeader Subtask New' => '子任务添加',
    'smallHeader Edit' => '任务编辑',
    'smallHeader Subtask Edit' => '子任务编辑',
    'smallHeader Set' => '人员设置',
    'smallHeader Export' => '项目进度表导出',
    'smallHeader Upload' => '附件上传',
    'Add Task'  =>  '创建一级任务',
    'Edit Task' => '编辑任务',
    'Start Proj' => '启用项目',
    'Stop Proj' => '结项',
    'Delete Proj'   =>  '删除项目',
    //--------------表单-----------------
    'month' => '月份',
    'no_task' => '无上级任务',
    'add_two_task' => '添加子任务',
    'upper_level_task' => '上级任务',
    'primary_task' => '一级任务',
    'second_task' => '二级任务',
    'task_id' => '任务编号',
    'program_id' => '项目编号',
    'task_name' => '任务名称',
    'task_content'   =>  '任务内容',
    'contractor_id' => '承包商编号',
    'add_operator' => '添加操作员id',
    'status' => '状态',
    'record_time' => '创建日期',
    'STATUS_NORMAL' => '正常',
    'STATUS_STOP' => '结项',
    'task_user_set' => '成员',
    'attach_ment' => '附件',
    'upload'=> '附件上传',
    'attach_content'=> '附件内容',
    'plan_amount' => '计划量',
    'plan_rate' => '计划完成进度',
    'amount_unit' => '单位',
    'plan_work_hour' => '计划工时',
    'plan_start_time' => '计划开始时间',
    'plan_end_time' => '计划结束时间',
    'act_start_time' => '实际开始时间',
    'act_end_time' => '实际结束时间',
    'act_work_hour' => '实际工时',
    'task_user' => '参与人员',
    'work_date' => '日期',
    'search_contractor_id' => '查找承包商编号',
    'enter_contractor_name' => '请输入承包商名称',
    'sub_contractor_name' => '项目承包商',
    'contractor_name' => '项目总包商',
    'Assign SC' => '指定分包',
    'id' => '编号',
    'null' => '无',
    'confirm_stop'  =>  '确定结束项目吗？项目结束后将不能再次开启。',
    'contractor_type'   =>  '项目类型',
    'project_struct'    =>  '分包项目',
    'project_decomposition' => '项目分解',
    'project_sub_click' =>  '点击进行分包项目管理',
    'project_dec_click' => '点击进行分包项目任务分解',
    'Assign User' => '按岗位指定任务成员',
    'export_task_report'=> '导出任务报表',
    //-------------验证-----------------------
    'error_task_name_is_null' => '任务名称不能为空！',
    'error_task_id_is_null' => '任务编号不能为空！',
    'error_work_date_is_null' => '日期不能为空！',
    'error_task_date_is_end' => '此任务已过期！',
    'error_task_date_is_start' => '此任务还未开始',
    'error_task_user_is_null' => '请至少指定一名成员',
    'error_date_early' =>'开始日期必须晚于一级任务的开始日期',
    'error_date_late' =>'结束日期必须早于一级任务的结束日期',
    'delete_father_task'=>'是一级项目，子项目也会被删除，确认删除吗?',
);

