<?php

/**
 * 操作员管理
 * @author LiuXiaoyuan
 */
return array(
    //----------标题---------------
    'contentHeader' => '操作员管理',
    'bigMenu' => '系统管理',
    'smallHeader List' => '操作员列表',
    'smallHeader New' => '操作员添加',
    'smallHeader Edit' => '操作员编辑',
    'Add Operator' => '添加操作员',
    'Edit Operator' => '修改操作员',
    'Edit OperatorInfo' => '修改个人信息',
    'Edit Operator Pwd' => '修改登录密码',
    'Logout Operator' => '注销操作员',
    'Reset Operator Pwd' => '重置操作员密码',
    //---------表单----------------
    'Base Info' => '基本信息',
    'Login Info' => 'Webpage登录信息',
    'Face Login Info' => 'FACE登录信息',
    'Operator' => '登录账号',
    'Passwd' => '新密码',
    'Passwd_c' => '确认密码',
    'Init Passwd' => '初始密码',
    'Name' => '姓名',
    'Phone' => '电话',
    'Email' => 'E-mail',
    'Operator Type' => '操作员类型',
    'Operator Role' => '角色',
    'Last Login IP' => '上次登录IP',
    'Last Login Time' => '上次登录时间',
    'Unreg Time' => '注销时间',
    'Reg Time' => '注册时间',
    'Status' => '状态',
    'Record Time' => '入库时间',
    'Action' => '操作',
    'STATUS_NORMAL' => '正常',
    'STATUS_DISABLE' => '已注销',
    'TYPE_SYSTEM' => '系统管理员',
    'TYPE_PLATFORM' => '承包商管理员',
    'Button Save' => '保存',
    'Button Back' => '返回',
    'Select Type' => '-选择类型-',
    'Select Role' => '-选择角色-',
    'zh_CN' => '中文',
    'en_US' => '英文',
    'Language' => '语言',
    'Contractor Id' => '承包商编号',
    'Old Passwd' => '原密码',
    'default_program' => 'Default attendance project office',
    'default_program_content' => 'The office personnel attendance is special',
    'Role' => '角色',
    'maincomp' => '总包公司',
    'subcomp' => '分包公司',
    'Select MC' => '-选择总包公司-',
    'Select SC' => '-选择分包公司-',
    'contractor_name' => '承包商公司',
    'role_id' => '角色',
    
    //-----------验证信息----------------
    'Error Code is wrong'   =>  '验证码输入错误。',
    'Error operator_type is null' => '请选择操作员类型。',
    'Error role_id is null' => '请选择角色。',
    'Error operator_name is null' => '请输入姓名。',
    'Error old password is null' => '请输入原密码。',
    'Error contractor_id is null' => '请输入承包商编号',
    'Error contractor_id is not exist' => '不存在此承包商编号。',
    'Error old password is error' => '原密码错误。',
    'Error operator_id is null' => '请输入登录账号。',
    'Error password is null' => '请输入新密码。',
    'Error password_ic is null' => '请输入确认密码。',
    'Error pwd is not eq' => '密码不一致！',
    'Error operator_id is exist' => '该登录账号已存在。',
    'Success Resetpwd' => '重置密码成功！新密码123456，请登录系统修改。',
    'Confirm Logout_1' => '确认要注销：',
    'Confirm Logout_2' => ' 吗？',
    'Loading' => '正在获取数据...',
    'password info' => '若不修改请留空',
    'enter_contractor_name' => '请输入承包商名称'
    
    
);
