<?php

/**
 * 人员管理
 * @author liuminchao
 */
return array(
    //----------标题---------------
    'contentHeader' => '工时查询',
    'contentHeader_set' => '工时设置',
    'contentHeader_wage' => '时薪设置',
    'contentHeader_allowance' => '补贴设置',
    'contentHeader_salary'=> '工资查询',
    'contentHeader_salary_calculate'=> '工资计算',
    'contentHeader_salary_query'=> '工资查询',
    'contentHeader_salary_storage'=> '工资审核',
    'contentHeader_export_salary'=> '工资结算报表',
    'bigMenu' => '薪资设置',
    'smallHeader Edit'=> '工资编辑',
    'smallHeader List' => '工时列表',
    'smallHeader Wage List'=> '岗位时薪列表',
    'smallHeader Allowance List'=> '员工补贴列表',
    'smallHeader Salary List'=> '员工工资列表',
    //---------表单----------------
    'working_date' => '工作日期',
    'export_month' => '月份',
    'program' => '项目',
    'wage' => '时薪',
    'allowance' => '补贴金额',
    'allowance_content' => '补贴明细',
    'date' => '补贴日期',
    'allowance_type' => '补贴类型',
    'wage_overtime' => '加班时薪',
    'user_name' => '用户姓名',
    'user_phone'=> '用户电话',
    'work_hours' => '基本工时',
    'overtime_hours' => '加班工时',
    'status' => '状态',
    'edit_wage' => '编辑',
    'detail_wage' => '详细',
    'start_date' => '开始日期',
    'end_date' => '结束日期',
    'wage_date'=> '工资日期',
    'basic_wage'=>  '基本工资',
    'overtime_wage'=> '加班工资',
    'deduction_wage'=> '扣款金额',
    'total_wage'=> '工资总额',
    'STATUS_CONFIRM' => '已确认',
    'STATUS_UNCONFIRMED' => '未确认',
    'STATUS_DISSENT' => '异议',
    'STATUS_NORMAL' => '已审核',
    'STATUS_DISABLE' => '未审核',
    'record_time' => '记录日期',
    'log_time' => '记录日期',
    'Add Allowance'=> '添加员工补贴',
    'Staff_workhour_export'=> '工时统计报表',
    'Salary_export' => '工资结算报表',
    'attend_hour_total'=> '工时汇总',
    'confirm_delete'=> '确定删除该员工此项补贴吗',
    'success_calculate'=> '计算成功',
    'error_calculate'=> '计算失败',
    'maintain_calculate'=>'该日期工资已经入库',
    'button_calculate'=>'计算',
    'button_audit'=>'审核',
    'button_set'=>'工资设置',
    'success_storage'=>'入库成功',
    'error_storage'=>'入库失败',
    'No_allowance'=>'暂无补贴',
    //-----------验证信息----------------
    'date_null'=> '日期不能为空',
    'salary_audit_exist'=> '该工资已经入库无法审核',
    'query_date_null'=> '查询日期不为空',
    'Error start_date is null' => '请输入开始日期。',
    'Error end_date is null' => '请输入结束日期。',
    'Error user_phone is null' => '该员工不存在',
    'Error now_day is last' => '结束日期请选择在当日之前的一天',
    'alert_hours'=> '请填写工时数',
    'ation_type'=> '请选择国籍类型',
    'alert_wage'=> '请填写时薪',
    'alert_overtimewage' =>'请填写加班时薪',
    'error_workhour_update' => '该工时已审核，无法修改',
    'error_user_name_is_null' => '请填写用户姓名',
    'error_user_phone_is_null' => '请填写用户手机号码',
    'error_allowance_is_null' => '补贴金额不为空',
    'error_allowance_date_is_null' => '补贴日期不为空',
    'error_insert_allowance' => '该日期工资已入库，无法添加补贴',
    'error_update_allowance' => '该日期工资已入库，无法修改补贴',
    'error_delete_allowance' => '该日期工资已入库，无法删除补贴',
    'calculate_prompt' => '注意：不填写用户电话，计算的是全部员工的工资，填写用户电话，计算的是该用户的工资',
    'storage_prompt' => '注意：不填写用户电话，审核的是全部员工的工资，填写用户电话，审核的是该用户的工资',
    'allowance_prompt' => '注意：不填写用户电话，填写的是全部员工的补贴，填写用户电话，填写的是该用户的补贴',
);