<?php

/**
 * 公用
 * @author LiuMinchao
 */
return array(
    'dboard' => '质量检查',
    'smallHeader List' => '检查单列表',
    'contentHeader' => '例行检查',
    'bigMenu' => '安全单',
    'program' => '项目',
    'company' => '公司',
    'STATUS_ONGOING' => '申请',
    'STATUS_ASSESS' => '已审批',
    'STATUS_RECEIVE' => '已接收',
    'STATUS_REJECT' => '已拒绝',
    'STATUS_TIMEOUT_CLOSE' => '超时强制关闭',
    'check_id' => '检查单编号',
    'device_name' => '设备名称',
    'check_type' => '检查类型',
    'form_type' => '表单类型',
    'root_proname' => '总包项目名称',
    'status' => '状态',
    'apply_date' => '申请日期',
    'apply_time' => '申请时间',
    'stipulation_time' => '规定时间',
    'violation_record' => '违规记录',
    'violation_photo' => '违规拍照',
    'safety_level' => '安全等级',
    'export' => '导出',
    'Export Pdf' => '导出安全报告',
    'check_kind' => '检查种类',
    'applicant_name' => '申请人',
    'date_of_application' => '申请时间',

    'export_title' => 'BORED PILE RECORD',
    'export_block' => 'Block / Zone',
    'export_project' => 'Project',
    'export_ietm_no' => 'Item (Pile ref No.)',
    'export_sheet_no' => 'Inspection Sheet No',
    'export_gridline' => 'Gridline',
    'export_boring' => 'Boring Date',
    'export_rig_no' => 'Rig No.',
    'export_sheet_no' => 'Sheet No.',
    'export_casting_date' => 'Casting Date',
    'export_bore_log' => 'BORE LOG',
    'export_length' => 'Length (m)',
    'export_soil' => 'Soil Description',
    'export_remark' => 'Remarks:',
    'Prepared By' => 'Prepared By:',
    'Checked By' => 'Checked By:',
    'Approved By' => 'Approved By:',
    'Name & Signature of Contractors' => 'Name & Signature of Contractors',
    'Name & Signature of RTO' => 'Name & Signature of RTO',
    'Name & Signature of Resident Engineer' => 'Name & Signature of Resident Engineer',
    'Signature' => 'Signature',
    'rep_time' => 'Rep. Date & Time',
    'Date & Time' => 'Date & Time',
    'qa_report' => 'Qa Report',
    'merge_report' => '下载合并报告',
    'attachment' => '附件',
);