<?php

/**
 * 操作员管理
 * @author LiuMinchao
 */
return array(
    //--------------标题-----------------
    'contentHeader' => '总包项目',
    'sub contentHeader' => '分包项目',
    'bigMenu' => '项目管理',
    'smallHeader List' => '项目列表',
    'smallHeader New' => '项目添加',
    'smallHeader Edit' => '项目编辑',
    'Add Proj' => '创建新项目',
    'Add Sub Proj'  =>  '创建分包',
    'Edit Proj' => '修改项目',
    'Start Proj' => '启用项目',
    'Stop Proj' => '结项',
    'Delete Proj'   =>  '删除项目',
    'Project Set' => '项目设置',
    //--------------表单-----------------
    'num' => '序号',
    'program_id' => '编号',
    'program_name' => '项目名称',
    'program_content'   =>  '项目内容',
    'program_address' => '项目位置',
    'program_amount' => '项目金额',
    'program_construction_no' => '项目施工编号',
    'program_construction_no' => '项目BP编号',
    'construction_start' => '施工开始日期',
    'construction_end' => '施工结束日期',
    'contractor_id' => '承包商编号',
    'add_operator' => '添加操作员id',
    'status' => '状态',
    'record_time' => '创建日期',
    'STATUS_NORMAL' => '正常',
    'STATUS_STOP' => '结项',
    'STATUS_DELETE' => '删除',
    'attachment' => '附件',
    'document' => '文档',
    'search_contractor_id' => '查找承包商编号',
    'enter_contractor_name' => '请输入承包商名称',
    'sub_contractor_name' => '项目承包商',
    'contractor_name' => '项目总包商',
    'Assign SC' => '指定分包',
    'subcon_type' => '分包类型',
    'id' => '编号',
    'null' => '无',
    'confirm_stop'  =>  '确定结束项目吗？项目结束后将不能再次开启。',
    'mc_confirm_stop_1'  =>  '确定结束项目',
    'mc_confirm_stop_2'  =>  '吗？项目结束后将不能再次开启。',
    'sc_confirm_stop_1'  =>  ' 确定要结束分包 ',
    'sc_confirm_stop_2'  =>  ' 从项目 ',
    'sc_confirm_stop_3'  =>  '里吗？项目结束后将不能再次开启。',
    'contractor_type'   =>  '项目类型',
    'project_struct'    =>  '分包项目',
    'project_decomposition' => '项目分解',
    'project_region' => '项目区域',
    'region' => '区域',
    'Add Region' => '增加区域',
    'Del Region' => '删除区域',
    'Set Region' => '设置区域',
    'Level 1 area' => '一级区域',
    'Level 2 area' => '二级区域',
    'project_sub_click' =>  '分包列表',
    'project_dec_click' => '点击进行分包项目任务分解',
    'subcon_alert' => '选择分包类型，创建分包后在成员选择上只选择相关岗位成员。不选择分包类型，无岗位限制',
    'struct' => '组织图',
    'way_attendance' => '考勤方式',
    'start_sign' => '开启考勤',
    'start_face' => '飞搜考勤',
    'close_face' => '关闭考勤',
    'start_app'  => '考勤机考勤',
    'tbm_sign' => '将faceapp数据作为TBM入口数据',
    'update_faceset' => '更新飞搜',
    'start_attendance' => '云端考勤',
    'project_document' => '项目文件',
    'independent' => '承包商类型',
    'independent_no' => '总包',
    'location_require_no' => '关闭',
    'location_require_yes' => '开启',
    'independent_yes' => '独立分包',
    'set_attendance' => '考勤设置',
    'add' => '添加',
    'Base Info' => '基本信息',
    'Params Info' => '参数信息',
    'ptw_mode' => 'PTW流程',
    'tbm_mode' => 'TBM流程',
    'acci_mode' => 'ACCI流程',
    'wsh_mode' => 'WSH流程',
    'train_mode' => 'TRAIN/MEETING流程',
    'location_requires' => '位置服务',
    'in_staffs' => '入场人数',
    'out_staffs' => '待入场人数',
    'in_devices' => '入场设备数',
    'out_devices' => '待入场设备数',
    'Module Settings' => '模块设置',
    'params' => '参数设置',
    'report' => '报告设置',
    'struct_progress' => '结构进度',
    'arch_progress' => '装修进度',
    'me_progress' => '机电进度',
    'program_gfa' => '项目占地面积',
    'developer_client' => '发展商/业主',
    'consultant' => '顾问',
    //-------------验证-----------------------
    'error_block_is_null' => '主区域不能为空! ',
    'error_projid_is_null' => '项目编号不能为空！',
    'block is null' => '区域不能为空！',
    'error_proj_name_is_null' => '项目名称不能为空！',
    'error_projid_is_exists' => '该项目编号已存在！',
    'error_projname_is_exists' => '该项目名称已存在！',
    'error_subproj_is_exist'  =>    '该项目还有未结束的分包项目，不能结束。',
    'end_projuser_is_exist'  => '请确保所有工人/员工已经从此项目中出场。',
    'end_sc_projuser_is_exist'  => '请确保所有工人/员工已经从此子项目中出场。',
    'error_subproj_is_exist1'   =>  '该项目还有分包项目，不能删除。',
    'delete_projuser_is_exist'   =>  '该项目还有项目组成员，不能删除。',
    
);

