<?php

/**
 * 分包指定项目到人
 * @author LiuMinchao
 */
return array(
    //--------------标题-----------------
    'contentHeader' => 'Project Management',
    'bigMenu' => 'Project Management',
    'smallHeader Member List' => 'Project Team Member',
    'smallHeader Device List' => 'Project Device Member',
    'smallHeader New' => 'Add Project',
    'smallHeader Edit' => 'Edit Project',
    'smallHeader Upload' => 'Upload',
    'smallHeader Certificate Edit' => 'Edit Certificate',
    'Add Proj' => 'Add Project',
    'Edit Proj' => 'Edit Project',
    'Start Proj' => 'Start up Project',
    'Stop Proj' => 'Stop Project',
    'project_team'  =>  'Manpower & Staffing',
    'pdf_title' => 'Information',
    //--------------表单-----------------
    'num' => 'NO.',
    'program_id' => 'Project NO.',
    'program_name' => 'Project Name',
    'contractor_id' => 'Contractor NO.',
    'add_operator' => 'Add Operator NO.',
    'status' => 'Status',
    'record_time' => 'Registration Date & Time',
    'STATUS_NORMAL' => 'Normal',
    'STATUS_STOP' => 'Stop',
    'search_contractor_id' => 'Search Contractor NO.',
    'enter_contractor_name' => 'Please enter Contractor Name.',
    'sub_contractor_name' => 'Sub-Constractor Name',
    'contractor_name' => 'Contractor',
    'Assign User' => 'Select project team member by designation',
    'select_cnt'    => 'Selected Count',
    'prc_cnt'    => 'PRC Count',
    'nts_cnt'    => 'NTS Count',
    'id' => 'NO.',
    'null' => 'None',
    'name'=> 'Name',
    'personel_name'=> 'Name',
    'company_name'=> 'Company',
    //'ra_role'=> 'Risk Assessment Role',
    'ra_role'=> 'RA Role',
    //'ptw_role'=> 'Permit-to-work Role',
    'ptw_role'=> 'PTW Role',
    'wsh_mbr_flag'=> 'WSH Committee Member',
//    'wsh_mbr_flag'=> 'WSH Member',
//    'meeting_flag'=> 'WSH/Toolbox Meeting Role',
    'meeting_flag'=> 'WSH/TBM Role',
//    'training_flag'=> 'Training/Meeting Role',
    'training_flag'=> 'Training/Meeting Role',
    'main_role'=> 'Primary Position',
    'first_role'=> 'First Appointment',
    'second_role'=> 'Second Appointment',
    'third_role'=> 'Third Appointment',
    'authority_set'=> 'Manpower & Staffing',
    'user_pdf'=> 'Download LOA',
    'already_select'=>'Already selected',
    'record_photos'=>'Record certificate photos',
    'hpme_id_photo'=> 'ID Photo',
    'ppt_photo' => 'Passport Photo',
    'csoc_photo'=> 'Csoc Photo',
    'bca_photo'=> 'Bca Photo',
    'personel_photo'=>'Photo',
    'related_people'=>'Add New Personnel',
    'bca_pass_no' => 'NRIC/FIN/WP No.',
    'Role_id' => 'Role',
    'Group' => 'Group',
    'entrance_apply'=>'Pending Submission',
    'entrance_pending'=>'Pending Admission',
    'entrance_success'=>'Normal',
    'entrance_fail'=>'Entrance Reject',
    'leave_pending'=>'Pending Exit',
    'leave_success'=>'Leave approval success',
    'leave'=>'Remove',
    'delete'=>'Delete',
    'device'=>'Equipment',
    'no_submit'=>'Currently Pending Submission',
    'people'=>'People',
    'back_program' => 'Return to Project List',
    'compress' => 'Batch Download',
    'header_title' => 'Letter of Appointment',
    'export' => 'Export Excel',
    'project_user_excel'=>'Employee project information sheet',
    'program_name' => 'Project',
    'entry_date' => 'Date Of Entry',
    'entry_number'=> 'Enter the number of',
    'batch_live'=> 'Batch ',
    'Submitted on' => 'Submitted on',
    'Approved on' => 'Approved on',
    'Approved by' => 'Approved by',
    'Approver Electronic Signature' => 'Approver Electronic Signature',
    'expiry_date' => 'ID/Pass Expiry Date',
    'csoc_date' => 'CSOC/AWSHCS Expiry Date',
    //-------------验证-----------------------
    'error_projid_is_null' => 'Project NO. can not be empty',
    'error_proj_name_is_null' => 'Project Name can not be empty',
    'error_projid_is_exists' => 'This Project NO. already exists!',
    'error_projname_is_exists' => 'This Project Name already exists!',
    'confirm_compress' => 'Download the PDF in a number of pages',
    'confirm_batch_live' => 'Batch Remove User in a number of pages',
    'error_tag_is_null' => 'Please select personnel',
    'error_project_user_null' => 'The project has no members',
);

