<?php

/**
 * 平台
 * @author LiuXiaoyuan
 */
return array(
    'contentHeader' => 'Overview',
    'Menu pedit' => 'Edit',
    'Menu reset' => 'Login password reset',
    'Menu logout' => 'Log Off',
    'Home' => 'Home',
    'no auth' => 'You have no permisson for this operation!',
    'smanager' => 'System Administrator',
    'cmanager' => 'Contractor Administrator',
    'Tip Password' => 'To ensure security, please modify your initial password',
    'Menu Operator' => 'Operator Management',
    'Menu Platform' => 'Platform number',
    'Menu Optlog' => 'System Log',
    'Menu System' => 'System Management',
    'Menu Maincomp' => 'Main-Contractor Management',
    'Menu Subcomp' => 'Sub-Contractor Management',
    'Menu Comp' => 'Contractor Management',
    'Menu CompInfo' => 'Information Management',
    'Menu Maincomp User' => 'Main-Constructor Stuff List',
    'Menu Maincomp Role' => 'Role Management',
    'Menu Main User' => 'Main-Constructor Stuff Management',
    'Menu Project List' => 'Project Management',
    'Menu Project MC'   =>  'Main Con Project',
    'Menu Project SC'   =>  'Sub-Con Project',
    'Menu Assign User' => 'Assigned Stuff',
    'Menu Project' => 'Project Management',
    'Menu Project Report'   =>  'Working Hours',
    'Menu Statistics' => 'Statistics',
    'Menu Notification' => 'Notification',
    'Menu Certexpiry' => 'Certificate Expiry',
    'Business Statistics' => 'Business Statistics',
    'Business Statistics Graph' => 'Business Statistics Graph',

    'Menu Comp Staff' => 'Personnel Management',
    'Menu Comp Worker' => 'Worker Management',
    'Menu Comp Role' => 'Department',
    'Menu Aptitude' => 'Qualification Query',
    'Menu Staff' => 'Personnel Details',
    'Menu My Project' => 'My Project',
    'Menu Workflow' => 'Workflow Setting',
    'Menu Licedown' => 'Download Report',
    'Menu Lice' => 'Permit-to-Work (PTW)',
    'Enter' => 'More info',
    'Prev' => 'Previous Page',
    'Next' => 'Next Page',
    'loading' => 'loading...',
    'Project Statistical Charts' => 'Project Statistics',
    'Company Statistical Charts' => 'Contractors Statistics',
    'PTW Type Statistics' => 'PTW Type Statistics',
    'NCR Type Statistics' => 'NCR Type Statistics',
    'Good Practices Statistics' => 'Good Practices Statistics',
    'Test Charts'  => 'PTW Status Statistics',
    'Menu Violation Ranking' => 'Violation Ranking',
    'Menu Meetingdown' => 'Download Report',
    'Menu Meeting' => 'Toolbox Meeting (TBM)',
    'Menu Meetingdown Plan' => 'Toolbox Meeting Plan',
    'Menu Safety Promotion Programme' => 'Safety Promotion Programme',
    'Menu Wshdown' => 'Download Report',
    'Menu Wsh' => 'WSH Inspection',
    'Menu Qaqcdown' => 'Download Report',
    'Menu Qaqc' => 'QA/QC Inspection',
    'Menu Training' => 'Download Report',
    'Menu Train' => 'Training',
    'Menu meeting' => 'Meeting',
    'Menu Accident down' => 'Download Report',
    'Menu Accident' => 'Incident',

    'Menu Attend'   =>  'Attendance',
    'Menu Attend2'  =>  'Attendance Management',
    'Menu Attend device'=>  'Equipment Control',
    'Menu Attend dayManage'=>  'Shift Management',
    'Menu Attend policyManage'=>  'Shift Allocation',
    'Menu Attend schedule'=>  'Attendance Rules',
    'Menu Attend manual'=>  'Manual Attendance',
    'Menu Attend record'=>  'Attendance Records',
    'Menu Attend failure record' => ' Failure Records',
    'Menu Attend report'=>  'Attendance Summary',
);
