<?php

/**
 * 薪资
 * @author liuminchao
 */
return array(
    //----------标题---------------
    'contentHeader' => 'Workhour Query',
    'contentHeader_set' => 'Workhour Set',
    'contentHeader_wage' => 'Wage Set',
    'contentHeader_allowance' => 'Allowance Set',
    'contentHeader_salary'=> 'Wages Query',
    'contentHeader_salary_calculate'=> 'Wages Calculation',
    'contentHeader_salary_query'=> 'Wages Query',
    'contentHeader_salary_storage'=> 'Wages Audit',
    'contentHeader_export_salary'=> 'Wage Settlement Report',
    'bigMenu' => 'Salary Setting',
    'smallHeader List' => 'Workhor List',
    'smallHeader Edit'=> 'Wage Edit',
    'smallHeader Wage List'=> 'Post Wage List',
    'smallHeader Allowance List'=> 'Employee Compensation List',
    'smallHeader Salary List'=> 'Employee Wages List',
    //---------表单----------------
    'working_date' => 'Work Date',
    'export_month' => 'Month',
    'program' => 'Program',
    'wage' => 'Wage',
    'allowance' => 'Allowance',
    'allowance_content' => 'Allowance Detail',
    'date' => 'Allowance Date',
    'wage_overtime' => 'Overtime Wage',
    'user_name' => 'Name',
    'user_phone'=> 'User Pone',
    'work_hours' => 'Base Time',
    'overtime_hours' => 'Overtime Hour',
    'status' => 'Status',
    'edit_wage' => 'Edit',
    'detail_wage' => 'Detail',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    'wage_date'=> 'Pay Date',
    'basic_wage'=>  'Basic Wage',
    'overtime_wage'=> 'Overtime Wage',
    'deduction_wage'=> 'Amount',
    'total_wage'=> 'Total Wage',
    'STATUS_CONFIRM' => 'Confirmed',
    'STATUS_UNCONFIRMED' => 'Unconfirmed',
    'STATUS_DISSENT' => 'Dissent',
    'STATUS_NORMAL' => 'Approved',
    'STATUS_DISABLE' => 'Unapprove',
    'record_time' => 'Date Created',
    'record_time' => 'Record Date',
    'log_time' => 'Record Date',
    'Add Allowance'=> 'Add Staff Allowance',
    'Staff_workhour_export'=> 'Working hours statistics',
    'Salary_export' => 'Wage Settlement Report',
    'attend_hour_total'=> 'man-hour collection',
    'confirm_delete'=> 'Confirm to Delete the employee the subsidy?',
    'success_calculate'=> 'Successfully calculated!',
    'error_calculate'=> 'Calculate Failed',
    'maintain_calculate'=>'The date of wages has been put in storage',
    'button_calculate'=>'Calculate',
    'button_audit'=>'Storage',
    'button_set'=>'Salary setting',
    'success_storage'=>'Successfully storaged!',
    'error_storage'=>'Storage Failed',
    'No_allowance'=>'Temporarily no allowance',
    //-----------验证信息----------------
    'date_null'=> 'The date can not be empty',
    'salary_audit_exist'=> 'The salary has been put in storage cant review',
    'query_date_null'=> 'Query the date is not empty',
    'Error start_date is null' => 'Please input start date.',
    'Error end_date is null' => 'Please input end date.',
    'Error user_phone is null' => 'The employee does not exist',
    'Error now_day is last' => 'End date, please choose one day before the day',
    'alert_hours'=> 'Please fill in the number of working hours',
    'ation_type'=> 'Please select nation type',
    'alert_wage'=> 'Please fill the wage',
    'alert_overtimewage' =>'Please fill the overtime wage',
    'error_workhour_update' => 'The time has been checked, cannot be modified',
    'error_user_name_is_null' => 'Please fill the user name',
    'error_user_phone_is_null' => 'Please fill the user phone',
    'error_allowance_is_null' => 'Subsidies is not null',
    'error_allowance_date_is_null' => 'Date of subsidies is not empty',
    'error_insert_allowance' => 'The date of wages has been put in storage, could not add subsidies',
    'error_update_allowance' => 'The date of wages has been put in storage, cannot be modified',
    'error_delete_allowance' => 'The date of wages has been put in storage, could not remove subsidies',
    'calculate_prompt' => 'Note: do not fill in the user calls, calculation is the salary of all employees, fill in the user calls, the calculation is the their salary',
    'storage_prompt' => 'Note: do not fill in the user calls, the audit is the salary of all employees, fill in the user calls, audit is the their salary',
    'allowance_prompt' => 'Note: do not fill in the user calls, fill in all the their allowance, fill in the user calls, fill in the their subsidies',
);