<?php

/**
 * 人员管理
 * @author liuminchao
 */
return array(
    //----------标题---------------
    'contentHeader' => '设备管理',
    'contentHeader_set' => '工时设置',
    'bigMenu' => '设备管理',
    'smallHeader List' => '设备列表',
    'smallHeader New' => '设备添加',
    'smallHeader Edit' => '设备编辑',
    'Statistics contentHeader' => '设备统计',
    //---------表单----------------
    'device_edit' =>'编辑',
    'device_delete' => '删除',
    'device_type' => '设备类型',
    'device_name' => '设备名称',
    'device_content' => '设备内容',
    'device_id' => '设备编码',
    'device_img'=> '设备图片',
    'permit_img'=> '许可证图片',
    'permit_info'=> '许可证信息',
    'permit_startdate'=>'许可证起始日期',
    'permit_enddate'=> '许可证截止日期',
    'next_service_date' => '下次维修日期',
    'status' => '状态',
    'Action' => '操作',
    'device_num' => '设备数量',
    'record_time' => '入库时间',
    'Add Equipment' => '添加设备',
    'Logout Device' =>'删除设备',
    'Edit Device' =>'修改设备',
    'STATUS_NORMAL'=> '已启用',
    'STATUS_DISABLE'=> '未启用',
    'select'=>'选择',
    'submit'=>'提交',
    'related_device'=>'关联入场设备',
    'Assign Device' => '按设备类型指定项目设备',
    'select_cnt'    => '已选设备数',
    'Equipment_certificate' => '设备证书',
    'Equipment_batch_export' => '批量导出设备表',
    'safe_working_load' => '安全工作负载(KG)',
    'test_load' => '测试负载(KG)',
    'External ConSASS audit summary' => 'External ConSASS audit summary',
    'Proposed Audit Date' => 'Proposed Audit Date',
    'Actual Audit Date' => 'Actual Audit Date',
    'Audit Company' => 'Audit Company',
    'Remarks' => 'Remarks',
    'Register' => 'Register',
    'Scaffold register' => 'Scaffold Register',
    'Ladder register' => 'Ladder Register',
    'Crane data logger report summary' => 'Crane Data Logger Report Summary',
    'scaffold_type' => 'Scaffold Type',
    'height' => 'Height',
    'week_1' => 'Week-1',
    'week_2' => 'Week-2',
    'week_3' => 'Week-3',
    'week_4' => 'Week-4',
    'week_5' => 'Week-5',
    'dismantle_date' => 'Dismantled on(Date)',
    'location' => 'Location',
    'inspected_by' => 'Inspected by',
    'scaffold_type' => 'Scaffold Type',
    'ladder_no' => 'Ladder No.',
    'ladder_type' => 'Ladder Type',
    'height' => 'Height',
    'using_by' => 'Using By(Company)',
    'distinctive_no' => 'Distinctive No.',
    'serial_no' => 'Serial No.',
    'type' => 'Type/Description',
    'swl' => 'SWL',
    'lm_no' => 'LM No.',
    'bypass_times' => 'No. of bapass times',
    'max_time' => 'Maximum Overload Time',
    'min_time' => 'Minimum Overload Time',
    'reason' => 'Reason for Overload',
    'owner' => 'Crane Owner',
    'monthly' => 'Monthly',
    'quarter' => 'Once every 3 months',
    'Deactivate' => '不可见',
    'Activate' => 'Activate',
    //-----------验证信息----------------
    'Error Equipment_id is null'=> '设备编码为空',
    'Error Equipment_name is null'=> '设备编码为空',
    'Error Upload_file is null' => '请先上传文件',
    'Error Equipment_id is exist' => '该设备编号已存在。',
    'Error Upload_pic is null' => '请先上传图片',
    'Error Equipment_type is null' => '设备类型不能为空',
    'Error Device_content is null' => '证书描述不能为空',
    'Error device is in program' =>  '该设备还有未完结的项目:',
    'Error device do not' => '不能操作',
    'Error Device is exist' => '设备编码已经存在于 ',
);