<?php

/**
 * 许可证
 * @author LiuXiaoyuan
 */
return array(
    'contentHeader' => 'Download Report',
    'bigMenu' => 'PTW ',
    'smallHeader List' => 'PTW Records',
    'apply_id' => 'Apply Id',
    'program_name' => 'Project',
    'company' => 'Company',
    'ptw_title' =>  'Title',
    'ptw_type' =>  'PTW Type',
    'contractor_name' => 'Applicant Company',
    'main_contractor' => 'Total package company',
    'root_program' => 'The contractor project',
    'apply_date' => 'Date of Application',
    'apply_id' => 'No.',
    'status' => 'Status',
    'work_content' => 'Work to be performed',
    'continue_time' => 'Duration',
    'from' => 'From',
    'to' => 'To',
    'total' => 'Total',
    'day' => 'days',
    'from_time' => 'Commentcement Time',
    'to_time' => 'Stoppage Time',
    'condition_list' => 'SAFETY CONDITIONS',
    'condition_name' => 'SAFETY CONDITIONS',
    'worker_list' => 'Application for Permit-to-Work',
    'seq' => 'S/N',
    'name' => 'Name',
    'worker_name' => 'Name of Workers',
    'wp_no' => 'WP No.',
    'progress_list' => 'Approval Process',
    'progress_close_list' => 'Approval Close Step',
    'audit_person' => 'Approver',
    'audit_result' => 'Approval Result',
    'agree' => 'Agree',
    'disagree' => 'Disagree',
    'rejected' => 'Rejected',
    'wait' => 'Wait',
    'audit_date' => 'Approval Date',
    'STATUS_REVISE' => 'Revising',
    'download' => 'Download',
    'downloadtwo' => 'Download2',
    'STATUS_AUDITING' => 'Submitted',
    'STATUS_FINISH' => 'Approved',
    'STATUS_REJECT' => 'Rejected',
    'STATUS_REVOKED'=> 'Revoked',
    'STATUS_CLOSE_AUDITING' => 'Closure Approved',
    'STATUS_CLOSE_FINISH' => 'Completed',
    'STATUS_CLOSE_REJECT' => 'Closure Rejected',
    'worker_name' => 'Worker Name',
    'ptw_report' => 'PTW Report',
    'checklist_report' => 'Checklist Report',
    'time_period' => 'Please select time period',
    'condition_id_is_null' => 'Condition Id can not be empty!',
    'Ptw_record_export' => 'PTW Report',
    'submitted' => 'Submitted',
    'assessed' => 'Assessed',
    'assessed2' => 'Assessed 2',
    'approved' => 'Approved',
    'rejected' => 'Rejected',
    'closed' => 'Closed',
    'closure approved' => 'Closure Approved',
    'closure approve' => 'Closure Approve',
    'closure accepted' => 'Closure Accepted',
    'closure rejected' => 'Closure Rejected',
);

