<?php

/**
 * 工具箱会议
 * @author LiuXiaoyuan
 */
return array(
    'contentHeader' => 'Download Report',
    'bigMenu' => 'Incident',
    'smallHeader List' => 'Incident Records',
    'report_title' => 'Incident Report',
    'seq' => 'No.',
    'title' => 'Title',
    'accident_details' => 'Injury Details',
    'meeting_date' => 'Training Date',
    'status' => 'Status',
    'program_name' => 'Project',
    'company' => 'Company',
    'mid' => 'Meeting No.',
    'progress_list' => 'Approval Process',
    'audit_person' => 'Approver',
    'audit_date' => 'Approval Date',
    'audit_result' => 'Approval Result',
    'type' => 'Type of work',
    'agree' => 'Agree',
    'disagree' => 'Disagree',
    'wait' => 'Wait',
    'content' => 'Content',
    'members' => 'Name',
    'apply_date' => 'Date of Application',
    'accident_type'=> 'Type',
    'record_time' => 'Created Date',
    'accident_info'=> 'Incident Summary',
    'detail' => 'Details',
    'role' => 'Position',
    'equipment' => 'Equipment',
    'type' => 'Type',
    'leave_info' => 'Sick Leave',
    'accident_location' => 'Event Location',
    'accident_person' => 'Personnel Involved',
    'accident_equipment' => 'Equipment Involved',
    'accident_process' => 'Event Details',
    'accident_details' => 'Injury Details',
    'accident_confession' => 'Statement',
    'accident_summary' => 'Incident Summary',
    'accident_time' => 'Incident Time',
    'sick_leave_days'=> 'Sick Leave Days',
    'apply_user' => 'Creator',
    'apply_company' => 'Creator Company',
    'accident_photo'=> 'Photo(s)',
    'leave_start_date'=> 'Date Form',
    'leave_end_date'=> 'Date To',
    'sick_photo' => 'Photo(s)',
    'device_no' => 'Registration No.',
);
