<?php

/**
 * 公用
 * @author LiuMinchao
 */
return array(
    'sn'=> 'No.',
    'title'=> 'Title',
    'company'=>'Company (Responsible Person)',
    'dboard' => 'Download Report',
    'smallHeader List' => 'WSH Inspection Records',
    'contentHeader' => 'Download Report',
    'bigMenu' => 'WSH Inspection',
    'Pending_Review' => 'Pending Review',
    'STATUS_ONGOING' => 'Ongoing',
    'STATUS_CLOSE' => 'Closed',
    'STATUS_TIMEOUT_CLOSE' => 'Auto-closed (After 7 days)',
    'check_id' => 'Checklist number',
    'root_proname' => 'Project',
    'status' => 'Status',
    'apply_time' => 'Date of Initiation',
    'stipulation_time' => 'Deadline',
    'violation_record' => 'Title',
    'violation_photo' => 'Criminal photo',
    'safety_level' => 'Severity Level',
    'safety_type' => 'Type of Inspection',
    'safety_finding' => 'Type of Finding',
    'export' => 'Export',
    'Export Pdf' => 'Export safety reports',
    'merge_report' => 'Merge Report',
    'Initiator'=> 'Initiator',
    'Person In Charge'=> 'Person In Charge',
    'Person Responsible'=> 'Offender',
    'date_of_initiation' => 'Date of Initiation',
    'ranking' => 'Ranking',
    'user_name' => 'Offender',
    'person_in_charge_name' => 'Person In Charge',
    'violation_cnt' => "Offender's Violation Count",
    'date' => 'Date',
    'in' => 'In',
    'rank_alert' => 'The number of violations rose the most',
    'company_category_alert' => 'had the largest number of non-compliances.',
    'good_practices_alert' => 'has the most good practices on site.',
    'project_category_alert' => 'had the most non-compliance cases.Further training should be given to help personnel to understand the safety measures and adhere to the guidelines put in place.',
    'date_alert' => 'The latter date cannot be greater than the former',
    'error_tag_is_null' => 'Please select at least two records',
    'confirm_batch_export' => 'Merge selected records into one report?',
    'wsh_report' => 'WSH Report',
);