<?php

/**
 * 分包指定项目到人
 * @author LiuMinchao
 */
return array(
    //--------------标题-----------------
    'contentHeader' => '项目管理',
    'bigMenu' => '项目管理',
    'smallHeader Member List' => '项目组成员',
    'smallHeader Device List' => '项目组设备',
    'smallHeader New' => '项目添加',
    'smallHeader Edit' => '项目编辑',
    'smallHeader Upload' => '证书上传',
    'smallHeader Certificate Edit' => '证书修改',
    'Add Proj' => '添加项目',
    'Edit Proj' => '修改项目',
    'Start Proj' => '启用项目',
    'Stop Proj' => '停用项目',
    'project_team'  =>  '成员',
    'pdf_title' => '信息',
    //--------------表单-----------------
    'num' => '序号',
    'program_id' => '项目编号',
    'program_name' => '项目名称',
    'contractor_id' => '承包商编号',
    'add_operator' => '添加操作员id',
    'status' => '状态',
    'record_time' => '入库时间',
    'STATUS_NORMAL' => '正常',
    'STATUS_STOP' => '停用',
    'search_contractor_id' => '查找承包商编号',
    'enter_contractor_name' => '请输入承包商名称',
    'sub_contractor_name' => '分包名称',
    'contractor_name' => '承包商',
    'Assign User' => '按岗位指定项目组成员',
    'select_cnt'    => '已选人数',
    'prc_cnt'    => '其中PRC人数',
    'nts_cnt'    => 'NTS人数',
    'id' => '编号',
    'null' => '无',
    'name'=> '姓名',
    'personel_name'=> '员工姓名',
    'company_name'=> '公司名称',
    'ra_role'=> '风险评估角色',
    'ptw_role'=> '许可证角色',
    'ptw_role_1'=> '许可证第一角色',
    'ptw_role_2'=> '许可证第二角色',
    'wsh_mbr_flag'=> '安全委员会委员',
    'meeting_flag'=> '会议人角色',
    'training_flag'=> '培训会议角色',
    'main_role'=> '项目角色',
    'first_role'=> '第一角色',
    'second_role'=> '第二角色',
    'third_role' => '第三角色',
    'authority_set'=> '人员出入场设置',
    'user_pdf'=> '下载人员表',
    'already_select'=>'已申请',
    'record_photos'=>'证书记录照片',
    'hpme_id_photo'=> '身份证照片',
    'ppt_photo' => '护照照片',
    'csoc_photo'=> '安全证照片',
    'bca_photo'=> '准证照片',
    'personel_photo'=>'拍照记录',
    'related_people'=>'关联入场人员',
    'bca_pass_no' => '准证号码',
    'Role_id' => '岗位',
    'Group' => '团队',
    'entrance_apply'=>'未提交',
    'entrance_pending'=>'入场待审批',
    'entrance_success'=>'已入场',
    'entrance_fail'=>'入场拒绝',
    'leave_pending'=>'出场待审批',
    'leave_success'=>'出场审批成功',
    'leave'=>'出场',
    'delete'=>'删除',
    'device'=>'设备',
    'no_submit'=>'当前未提交',
    'people'=>'人',
    'back_program' => '返回项目',
    'compress' => '批量下载',
    'header_title' => '项目团队成员简介',
    'export' => '导出Excel',
    'project_user_excel'=>'员工项目信息表',
    'program_name' => '项目',
    'entry_date' => '入场日期',
    'entry_number'=> '入场人数',
    'batch_live'=> '批量出场',
    'Submitted on' => '提交日期',
    'Approved on' => '批准日期',
    'Approved by' => '批准人',
    'Approver Electronic Signature' => '批准人签名',
    'expiry_date' => '证书截止日期',
    'csoc_date' => '安全证书截止日期',
    //-------------验证-----------------------
    'error_projid_is_null' => '项目编号不能为空！',
    'error_proj_name_is_null' => '项目名称不能为空！',
    'error_projid_is_exists' => '该项目编号已存在！',
    'error_projname_is_exists' => '该项目名称已存在！',
    'alert_authority' => '请先进行权限选择!',
    'confirm_compress' => '按页数对PDF进行批量下载',
    'confirm_batch_live' => '按页数对人员批量申请出场',
    'error_tag_is_null' => '请选择人员',
    'error_project_user_null' => '该项目无成员',
);

