<?php

/**
 * 公用
 * @author LiuXiaoyuan
 */
return array(
    'personel_information' => 'Personal information',
    'device_information' => 'Equipment information',
    'name' => 'Name',
    'designation' => 'Designation',
    'id_pass' => 'ID/Pass Type',
    'certificate_content' => 'Certificate Content',
    'permit_start_date'=> 'Permit Start Date',
    'permit_end_date' => 'Permit End Date',
    'employment_information' => 'Employment Information',
    'program_information' => 'Project Information',
    'Project' => 'Project',
    //2019-03-12添加
    'Chart_type' => 'Chart Type',
    'Pie_Chart' => 'Pie Chart',
    'Bar_Chart' => 'Bar Chart',
    'out_history' => 'Deployment History',
    'entrance'=> 'In',
    'out' => 'Out',
    'type' => 'Type',
    'role' => 'Role',
    'cnt' => 'Cnt',
    'total' => 'Total',
    'no' => 'Registration No.',
    'export' => 'Export Excel',
    'month' => 'Month',
    'daily_statistics' => 'Daily statistics',
    'month_statistics' => 'Month statistics',
    'spatial_statistics' => 'Spatial Statistics',
    'file_statistics' => 'Document Statistics',
    'attribute_size' => 'Attribute Size',
    'flow_pic_size' => 'Flow Pic Size',
    'documnet_size' => 'Document Size',
    'total_size' => 'Total Size',
    'max_size' => 'Max Size',
    'attachment' => 'Attachment',
    'document' => 'Document',
    'flow_pic' => 'Flow Pic',
    //--------------------------日报表------------------------
    'month_statistics' => 'Monthly Statistics',
    'day_statistics' => 'Daily Statistics',
    'date' => 'Date',
    'sc_program' => 'Company',
    'day_sum' => 'Cnt',
    'day_number'=> 'Number',
    'day_size'=> 'Size',
    'day_staffs' => 'Number of Staff',
    'day_toatl' => 'Total',
    'contentHeader_day' => 'Overview',
    'smallHeader List Day' => 'Daily Report',
    'smallHeader List Month' => 'Monthly Report',
    'bigMenu' => 'Statistics',
    'smallHeader List Company' => 'Contractor\'s statistical reports',
    'Business monthly statistics' => 'Business Monthly Statistics',
    'Business daily statistics' => 'Business Daily Statistics',
);

