<?php

/**
 * 操作员管理
 * @author LiuXiaoyuan
 */
return array(
    //--------------标题-----------------
    'contentHeader' => 'Main Con Project',
    'sub contentHeader' => 'Subcon List',
    'bigMenu' => 'Project Management',
    'smallHeader List' => 'Project List',
    'smallHeader New' => 'Add Project',
    'smallHeader Edit' => 'Edit Current Project',
    'Add Proj' => 'Add New Project',
    'Add Sub Proj'  =>  'Add Subcon',
    'Edit Proj' => 'Edit Project',
    'Start Proj' => 'Start up Project',
    'Stop Proj' => 'Project Concluding ',
    'Delete Proj'   =>  'Delete Project',
    'Project Set' => 'Restriction',
    //--------------表单-----------------
    'num' => 'NO.',
    'program_id' => 'No.',
    'program_name' => 'Project',
    'program_content'   =>  'Project Content',
    'program_address' => 'Project Address',
    'program_amount' => 'Project Value',
    'program_construction_no' => 'Project Construction No.',
    'program_bp_no' => 'Project BP No.',
    'construction_start' => 'Project Start Date',
    'construction_end' => 'Project End Date',
    'contractor_id' => 'Contractor Company NO.',
    'add_operator' => 'Add Operator ID',
    'status' => 'Status',
    'record_time' => 'Created On',
    'STATUS_NORMAL' => 'Ongoing',
    'STATUS_STOP' => 'Complete',
    'STATUS_DELETE' => 'Deleted',
    'attachment' => 'Attachment',
    'document' => 'Document',
    'search_contractor_id' => 'Search Contractor NO.',
    'enter_contractor_name' => 'Please enter Contractor Name.',
    'sub_contractor_name' => 'Subcon',
    'contractor_name' => 'Main Con',
    'Assign SC' => 'Add Subcon',
    'id' => 'NO.',
    'null' => 'None',
    'confirm_stop'  =>  'Are you sure to end item？After the project is over, the project will not be opened again.',
    'mc_confirm_stop_1'  =>  'Are you sure end the project ',
    'mc_confirm_stop_2'  =>  '? This action cannot be reversed once confirmed.',
    'sc_confirm_stop_1'  =>  ' Are you sure to end ',
    'sc_confirm_stop_2'  =>  ' for project ',
    'sc_confirm_stop_3'  =>  '? This action cannot be reversed once confirmed.',
    'contractor_type'   =>  'Project Type',
    'project_struct'    =>  'No. of Sub-Con',
    'project_decomposition' => 'Project Breakdown',
    'project_region' => 'Project Area',
    'region' => 'Region',
    'Add Region' => 'Add Region',
    'Del Region' => 'Delete Region',
    'Set Region' => 'Set Region',
    'Level 1 area' => 'Level 1 area',
    'Level 2 area' => 'Level 2 area',
    'project_sub_click' =>  'Subcon List',
    'project_dec_click' => 'Click on and embark on the Sub-Contractor Project decomposition',
    'subcon_alert' => 'Choose the subcontract type, create the subcontract on the members choose select only after related members, not to choose the subcontract type. no position limits',
    'struct' => 'Org Chart',
    'way_attendance' => 'Ways of attendance',
    'start_sign' => 'Open the attendance',
    'start_face' => 'CMS Face',
    'close_face' => 'Close CMS Face',
    'start_app'  => 'Attendance machine attendance',
    'update_faceset' => 'Update Faceset',
    'tbm_sign' => 'Use the faceapp data as TBM entry data',
    'start_attendance' => 'Cloud Attendance',
    'project_document' => 'Project File',
    'independent' => 'Contractor Type',
    'independent_no' => 'Main Contractor',
    'independent_yes' => 'Independent Sub-Contractor',
    'location_require_no' => 'OFF',
    'location_require_yes' => 'ON',
    'set_attendance' => 'Set Attendance',
    'add' => 'Add',
    'Base Info' => ' Project Information',
    'Params Info' => ' Project Params Information',
    'ptw_mode' => 'PTW',
    'tbm_mode' => 'TBM',
    'acci_mode' => 'Accident',
    'wsh_mode' => 'Inspection',
    'train_mode' => 'Training/Meeting',
    'location_requires' => 'Location Services',
    'in_staffs' => 'Appointed(Members)',
    'out_staffs' => 'Pending(Members)',
    'in_devices' => 'Appointed(Equipment)',
    'out_devices' => 'Pending(Equipment)',
    'Module Settings' => 'Module Settings',
    'params' => 'Module Settings',
    'report' => 'Report Format',
    'struct_progress' => 'Structural Progress',
    'arch_progress' => 'Architectural Progress',
    'me_progress' => 'M&E Progress',
    'program_gfa' => 'Program Gfa',
    'developer_client' => 'Developer Client',
    'consultant' => 'Consultant',
    'Additional Information' => 'Additional Information',
    //-------------验证-----------------------
    'error_block_is_null' => 'Primary area can not be empty! ',
    'error_projid_is_null' => 'Project NO. can not be empty!',
    'block is null' => 'Area cannot be empty！',
    'error_proj_name_is_null' => 'Project Name can not be empty',
    'error_projid_is_exists' => 'This Project NO. already exists!',
    'error_projname_is_exists' => 'This Project Name already exists!',
    'error_subproj_is_exist'  =>    'The Project have yet no finished project，cannot be end.',
    'end_projuser_is_exist'  => 'Please make sure all workers/staff have been removed from this project.',
    'end_sc_projuser_is_exist'  => 'Please make sure all workers/staff have been removed from this Sub-Contractor Project.',
    'error_subproj_is_exist1'   =>  'The Project have Sub-Contractor Project，cannot be deleted..',
    'delete_projuser_is_exist'   =>  'The project has team members, cannot be deleted.',
);

